server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bd_product
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    locations: classpath:db_migration
  jpa:
    hibernate:
      ddl-auto: validate