server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PedroScheurer/microservices-atitus.git
          search-paths: configs/{application}
          clone-on-start: true
          force-pull: true
        #native:
        #  search-locations: classpath:/configs/{application}