server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PedroScheurer/microservices-atitus.git
          search-paths: 'configs/{application}'
          clone-on-start: true
        native:
          search-locations: classpath:/configs/{application}